module.exports = {
  // api for get scheme
  getSchemeById: "SchemeDetails.usp_GetSchemeDetailsByID",
  
  // api for get master data
  AgeGroup: "sp_GetAgeGroupMasterForDropdown",
  BeneficiaryCategory: "sp_GetBeneficiaryCategoryMasterForDropdown",
  BeneficiaryType: "sp_GetBeneficiaryTypeMasterForDropdown",
  BenefitFrequency: "sp_GetBenefitFrequencyMasterForDropdown",
  BenefitType: "sp_GetBenefitTypeMasterForDropdown",
  DeliveryMechanism: "sp_GetDeliveryMechanismMasterForDropdown",
  Department: "sp_GetDepartmentMasterForDropdown",
  District: "sp_GetDistrictMasterForDropdown",
  DocumentRequired: "sp_GetDocumentMasterForDropdown",
  FinancialAssistanceType: "sp_GetFinancialAssistanceTypeMasterForDropdown",
  FundSharingPattern: "sp_GetFundSharingPatternMasterForDropdown",
  Gender: "sp_GetGenderMasterForDropdown",
  GeographicCoverage: "sp_GetGeographicCoverageMasterForDropdown",
  ImplementingAgency: "sp_GetImplementingAgencyMasterForDropdown",
  IncomeCriteria: "sp_GetIncomeCriteriaTypeMasterForDropdown",
  InsuranceType: "sp_GetInsuranceTypeMasterForDropdown",
  LocalBody: "sp_GetLocalBodyMasterForDropdown",
  Ministry: "sp_GetMinistryMasterForDropdown",
  Mission: "sp_GetMissionMasterForDropdown",
  MonitoringAgency: "sp_GetMonitoringAgencyMasterForDropdown",
  NationalPriority: "sp_GetNationalPriorityMasterForDropdown",
  Occupation: "sp_GetOccupationMasterForDropdown",
  OutcomeIndicator: "sp_GetOutcomeIndicatorMasterForDropdown",
  ReviewFrequency: "sp_GetReviewFrequencyMasterForDropdown",
  Scheme: "sp_GetSchemeMasterForDropdown",
  SchemePhase: "sp_GetSchemePhaseMasterForDropdown",
  SchemeStatus: "sp_GetSchemeStatusMasterForDropdown",
  SchemeType: "sp_GetSchemeTypeMasterForDropdown",
  SDG: "sp_GetSDGMasterForDropdown",
  Sector: "sp_GetSectorMasterForDropdown",
  ServiceMode: "sp_GetServiceModeMasterForDropdown",
  SocialCategory: "sp_GetSocialCategoryMasterForDropdown",
  StakeholderType: "sp_GetStakeholderTypeMasterForDropdown",
  State: "sp_GetStateMasterForDropdown",
  SubSector: "sp_GetSubSectorMasterForDropdown",
  TargetGroup: "sp_GetTargetGroupMasterForDropdown",
  Theme: "sp_GetThemeMasterForDropdown",
  UrbanRural: "sp_GetUrbanRuralMasterForDropdown",

  // api for insert scheme
  setSchemeMaster: "SchemeDetails.usp_InsertSchemeMaster",
  setSchemeObjectives: "SchemeDetails.usp_InsertSchemeObjectives",
  setSchemeClassification: "SchemeDetails.usp_InsertSchemeClassification",
  setSchemeBeneficiaries: "SchemeDetails.usp_InsertSchemeBeneficiaries",
  setSchemeEligibility: "SchemeDetails.usp_InsertSchemeEligibility",
  setSchemeFinancials: "SchemeDetails.usp_InsertSchemeFinancials",
  setSchemeImplementation: "SchemeDetails.usp_InsertSchemeImplementation",
  setSchemeGeography: "SchemeDetails.usp_InsertSchemeGeography",
  setSchemeTimeline: "SchemeDetails.usp_InsertSchemeTimeline",
  setSchemeBenefits: "SchemeDetails.usp_InsertSchemeBenefits",
  setSchemeComplementary: "SchemeDetails.usp_InsertSchemeComplementary",
  setSchemeConvergence: "SchemeDetails.usp_InsertSchemeConvergence",
  setSchemeOutcomes: "SchemeDetails.usp_InsertSchemeOutcomes",
  setSchemeSimilar: "SchemeDetails.usp_InsertSchemeSimilar",
  setSchemeSDG: "SchemeDetails.usp_InsertSchemeSDG",
  setSchemeStakeholders: "SchemeDetails.usp_InsertSchemeStakeholders",
  setSchemeRisks: "SchemeDetails.usp_InsertSchemeRisks",
  setSchemeMission: "SchemeDetails.usp_InsertSchemeMission",
  setSchemeRelationships: "SchemeDetails.usp_InsertSchemeRelationships",
  setSchemeDuplicate: "SchemeDetails.usp_InsertSchemeDuplicate",
  setSchemeState: "SchemeDetails.usp_InsertSchemeState",
  setSchemeDistrict: "SchemeDetails.usp_InsertSchemeDistrict",

  // api for update scheme
  updateSchemeMaster: "SchemeDetails.usp_UpdateSchemeMaster",
  updateSchemeObjectives: "SchemeDetails.usp_UpdateSchemeObjectives",
  updateSchemeClassification: "SchemeDetails.usp_UpdateSchemeClassification",
  updateSchemeBeneficiaries: "SchemeDetails.usp_UpdateSchemeBeneficiaries",
  updateSchemeEligibility: "SchemeDetails.usp_UpdateSchemeEligibility",
  updateSchemeFinancials: "SchemeDetails.usp_UpdateSchemeFinancials",
  updateSchemeImplementation: "SchemeDetails.usp_UpdateSchemeImplementation",
  updateSchemeGeography: "SchemeDetails.usp_UpdateSchemeGeography",
  updateSchemeTimeline: "SchemeDetails.usp_UpdateSchemeTimeline",
  updateSchemeBenefits: "SchemeDetails.usp_UpdateSchemeBenefits",
  updateSchemeComplementary: "SchemeDetails.usp_UpdateSchemeComplementary",
  updateSchemeConvergence: "SchemeDetails.usp_UpdateSchemeConvergence",
  updateSchemeOutcomes: "SchemeDetails.usp_UpdateSchemeOutcomes",
  updateSchemeSimilar: "SchemeDetails.usp_UpdateSchemeSimilar",
  updateSchemeSDG: "SchemeDetails.usp_UpdateSchemeSDG",
  updateSchemeStakeholders: "SchemeDetails.usp_UpdateSchemeStakeholders",
  updateSchemeRisks: "SchemeDetails.usp_UpdateSchemeRisks",
  updateSchemeMission: "SchemeDetails.usp_UpdateSchemeMission",
  updateSchemeRelationships: "SchemeDetails.usp_UpdateSchemeRelationships",
  updateSchemeState: "SchemeDetails.usp_UpdateSchemeState",
  updateSchemeDistrict: "SchemeDetails.usp_UpdateSchemeDistrict",
};
